### ISSUE TITLE
Can this be used on interfaces without MAC address?

### ISSUE THREAD

**Issue by dynek** [alsmith/multicast-relay#10]
Hey,

First of all thanks for the code!
I see a mac address is required for this code to run.
Is it really required by the protocol itself, cause I wanted to give it a try through wireguard and the interface doesn't have a MAC address.

Thank you

**Comment by dynek** [comment]
Not sure what to answer :-)

But yes I'd like to be able to control sonos' speakers via a (wireguard) VPN.

**Comment by alsmith** [comment]
The Sonos app doesn't want to send discovery packets over a VPN - it only wants to discover via Wifi.

Is your use-case something like this?

iPhone[SonosApp] - wifi1 - VPNclient -----internet----- VPNserver - wifi2 - SonosSpeakers

Or this:

iPhone[SonosApp + VPNApp] ----- 4G ----- VPNserver - wifi2 - SonosSpeakers

**Comment by dynek** [comment]
Yeah I know but if you are connected to WiFi and run WireGuard, 239.255.255.250/32 can be routed through the tunnel and the sonos app is somehow tricked. I can see the SSDP frames reach the other end of the tunnel:

Android[SonosApp + WiFi (for nothing) + VPN] ----- internet ----- VPNserver

**Comment by alsmith** [comment]
Got it. Let's see if this helps you out... https://github.com/alsmith/multicast-relay/tree/vpn

**Comment by dynek** [comment]
OK the app starts and I can see the frames going through.
They are relayed my router which does PIM but it doesn't seem to work.
I'm checking it. Thanks!

**Comment by dynek** [comment]
Hey @alsmith - I still haven't found a way to get all of this work with my setup @home but I can confirm my main router does receiving the UDP frames from the VPN server on which `multicast-relay` is running.
Thank you!
