### ISSUE TITLE
Include relay of NOTIFY in addition to M-SEARCH?

### ISSUE THREAD

**Issue by djpalmer11** [alsmith/multicast-relay#17]
https://github.com/alsmith/multicast-relay/blob/ca7db4ee8dde8c0186b24ac2d58fbf08df9978a3/multicast-relay.py#L320

                if origDestinationAddress == PacketRelay.SSDP_MCAST_ADDR \
                        and origDestinationPort == PacketRelay.SSDP_MCAST_PORT:
                    if  re.search(r'NOTIFY', data) or re.search(r'M-SEARCH', data):

This potentially decreases discovery time as a devices advertises itself and doesn't just respond to a search?

**Comment by alsmith** [comment]
@yo8192 can you comment?

**Comment by alsmith** [comment]
Sorted out in commit a152eca2beaf586d06fff958e42b8f62e428575a
