### ISSUE TITLE
ifFilter

### ISSUE THREAD

**Issue by juliodiz** [alsmith/multicast-relay#34]
Its possible to have ifFilter.json at master?

To filter 2 ways multicast traffic?

**Comment by alsmith** [comment]
Merged PR#35.

**Comment by juliodiz** [comment]
Perfect!

But ifFilter.json can be just one IP, without mask?

**Comment by alsmith** [comment]
Default is relay everything that is not in the ifFilter.json.

You can specify an IP address only now; if there is no / in the entry then /32 is assumed. Commit 503fc49.

**Comment by juliodiz** [comment]
Can be relay anything unless its on ifFilter.json ? 
That way can reduce the multicast doing just for what its necessary

**Comment by alsmith** [comment]
By default, if the src IP# can't be found in the filter then it gets relayed to all interfaces. If it is found then it will only be relayed to the interface(s) specified in the json.

**Comment by juliodiz** [comment]
"By default, if the src IP# can't be found in the filter then it gets relayed to all interfaces"
Its possible to not relay by default? Just what is in the file?

**Comment by alsmith** [comment]
There is an example in the repo: https://github.com/alsmith/multicast-relay/blob/master/ifFilter.json

**Comment by alsmith** [comment]
You could probably convince it to do no-relay by default by adding a "0.0.0.0/0": [] line.

**Comment by juliodiz** [comment]
Ohh ok! So i can use "0.0.0.0/0": [] at last line and this will block every other range or IP that its not before that line!
This should works!

Example: 
"10.0.0.0/20": ["br0", "br3"],
 "192.168.0.0/24": ["br2", "br3"],
 "192.168.1.1/32": ["br2"],
 "172.20.144.0/20": ["br0"]
"0.0.0.0/0": []

Thanks!

**Comment by juliodiz** [comment]
I try using
 "0.0.0.0/0": [],
 "10.125.128.0/17": ["eth1.10"],
 "10.125.1.0/24": ["eth1.5"]

But reflect others ranges or dev.

**Comment by juliodiz** [comment]
I try using this line but doesn't works.

{
 "10.125.128.0/17": ["eth1.10"],
 "10.125.1.0/24": ["eth1.5"],
  "0.0.0.0/0": []
}

**Comment by alsmith** [comment]
Can you say what doesn’t work ? Do you get an error message, or does it not behave in the way that you expect ?
Thanks!
Al.

**Comment by juliodiz** [comment]
Sorry, my bad!
I want to relay just 2 networks 10.125.128.0/17 and 10.125.1.0/24 for example.

10.125.128.0/17 relay to eth1.10
10.125.1.0/24 relay to eth1.5

All others networks and dev must be ignore.

Which is the best configuration for ifilter to do it?

**Comment by alsmith** [comment]
Hi there,

This ought to do the trick…

{"10.125.128.0/17": ["eth1.10"], "10.125.1.0/24": [“eth1.5”], "0.0.0.0/0": []}

However, I also committed a code change that makes searching the list end after the first match, otherwise the above wouldn’t work at all - do a git pull to pick it up.

Kind regards,
Al.

**Comment by juliodiz** [comment]
Empty log, nothing relayed.

{
	"10.125.128.0/17": ["eth1.10"],
	"10.125.1.0/24": ["eth1.5"],
	"0.0.0.0/0": []
 }


multicast-relay.py --interfaces eth1.5 eth1.10  --ifFilte fFilter.json --verbose --logfile /var/log/muticast.log 
Jul-11 12:21:04 multicast-relay.py INFO: Adding multicast relay for 239.255.255.250:1900 (SSDP)
Jul-11 12:21:04 multicast-relay.py INFO: Adding multicast relay for 224.0.0.251:5353 (mDNS)
Jul-11 12:21:04 multicast-relay.py INFO: Adding broadcast relay for 255.255.255.255:6969 (Sonos Discovery)

**Comment by juliodiz** [comment]
The filter must allowed just 10.125.128.0/17 and 10.125.1.0/24, not ignore (denied)
All other networks not in 10.125.128.0/17 10.125.1.0/24 must be ignore. I believe the filter do the opposite.

**Comment by VeniceNerd** [comment]
Hey guys,

has this ever been resolved? I'm trying to do exactly the same but not sure if a solution has ever been found?

**Comment by alsmith** [comment]
Ah coming back to this, I just realised that having a "0.0.0.0/0" line is probably just bad, because when python reads the JSON into a dictionary, the ordering is not going to necessarily be preserved, and because we do first-match wins, if the first entry happens to be 0.0.0.0/0 then it'll sit there and relay precisely nothing.

I'd recommend a more granular approach of specifying more precisely what you don't want to have relayed, rather than 0.0.0.0/0 as a catch-all.

**Comment by VeniceNerd** [comment]
> Ah coming back to this, I just realised that having a "0.0.0.0/0" line is probably just bad, because when python reads the JSON into a dictionary, the ordering is not going to necessarily be preserved, and because we do first-match wins, if the first entry happens to be 0.0.0.0/0 then it'll sit there and relay precisely nothing.
> 
> I'd recommend a more granular approach of specifying more precisely what you don't want to have relayed, rather than 0.0.0.0/0 as a catch-all.

So what would be the suggested way to include a network into ifFilter.json and basically tell it to not send any of it's traffic anywhere else? Because I we don't include the network in the ifFilter.json at all it will basically transmit to all other networks by default, right?

**Comment by VeniceNerd** [comment]
> Ah coming back to this, I just realised that having a "0.0.0.0/0" line is probably just bad, because when python reads the JSON into a dictionary, the ordering is not going to necessarily be preserved, and because we do first-match wins, if the first entry happens to be 0.0.0.0/0 then it'll sit there and relay precisely nothing.
> 
> I'd recommend a more granular approach of specifying more precisely what you don't want to have relayed, rather than 0.0.0.0/0 as a catch-all.

Hi @alsmith I'm still wondering if you happen to know how to implement a more granular approach of specifying more precisely what I don't wan't to be relayed.

Right now I only know how to tell a network to relay to a set of VLANS. I wonder if there is also a way to specific which networks are NOT supposed to forward anywhere. Are the additional parameters or commands one can use within the ifFilter.json?
