### ISSUE TITLE
VLAN Down and UP

### ISSUE THREAD

**Issue by juliodiz** [alsmith/multicast-relay#36]
Hello!

Me again! =)

If VLAN goes down and up again the script lost and don't find the interface : [Errno 6] 

Jun-14 16:41:32 multicast-relay.py INFO: [mDNS] Relayed 233 bytes from 10.125.1.20:5353 on eth1.10 [ttl 255] to 224.0.0.251:5353 via eth1.5/10.125.128.1
Jun-14 16:41:32 multicast-relay.py INFO: Error sending packet: [Errno 6] No such device or address

**Comment by alsmith** [comment]
Doing an `ifconfig eth1.5 down` followed by an `ifconfig eth1.5 up` has no effect. But I was able to reproduce this by also removing the vlan itself: `vconfig rem eth1.5` `vconfig add eth1 5`

**Comment by alsmith** [comment]
Fixed in 8146256.
