### ISSUE TITLE
modify udp packet is wrong and generates invalid udp

### ISSUE THREAD

**Issue by TinoLange** [alsmith/multicast-relay#37]
https://github.com/alsmith/multicast-relay/blob/503fc498894ede308ef98987f16fbcc68c87dc64/multicast-relay.py#L332

Hi!

The code above generates invalid, huge UDP packages.
The `+ data[ipHeaderLength:]` adds the whole packet (all after the header). That summand needs to be removed.

So correct line should just look like:
`ipHeader = data[:ipHeaderLength-8] + socket.inet_aton(srcAddr) + socket.inet_aton(dstAddr)`

Best regards

Tino

**Comment by alsmith** [comment]
Thanks for the report - fixed in 503fc49.

**Comment by juliodiz** [comment]
After this update the Netflix for example its not working. I will go deeper here to check. 

I back for previous version and everything working fine.
