### ISSUE TITLE
INFO: pre-made container of the bugFix branch for anyone who wants to test

### ISSUE THREAD

**Issue by scyto** [alsmith/multicast-relay#38]
https://hub.docker.com/r/scyto/multicast-relay/tags

Any one who tests this let me know if you see issues with the container or documentation on the container.
ill close this issue once we have confirmed branch fixes issue /u/rfg81 on reddit raised.

Issues can be logged here https://github.com/scyto/multicast-relay

**Comment by alsmith** [comment]
Thanks @scyto ! I just merged the fix for broadcast relaying into master.

**Comment by scyto** [comment]
@alsmith cool, I will update the container :latest version ASAP.
/u/rfg81 mentioned that there were some other fixes possibly pending.
If there are will you be maintain a dev branch?

**Comment by scyto** [comment]
Ok i updated the latest tag, can someone test and let me know it is ok.

https://hub.docker.com/r/scyto/multicast-relay/tags

**Comment by scyto** [comment]
closing as changes are now in master, my container is updated for anyone using it (it says 10k pulls which i find a little hard to believe tbh)

**Comment by alsmith** [comment]
Thanks @scyto !

**Comment by alsmith** [comment]
Hey @scyto there's a fix just gone in for anyone who uses --ssdpUnicastAddr
