### ISSUE TITLE
UnboundLocalError when using the ssdpUnicastAddr flag

### ISSUE THREAD

**Issue by kidhasmoxy** [alsmith/multicast-relay#40]
Upgraded to the latest commit off master, and now my container immediately crashes when using the ssdpUnicastAddr flag. I like using this flag to make my firewall rules simpler to manage, so hoping it isn't dropped. 

`
Traceback (most recent call last):

  File "multicast-relay.py", line 990, in <module>

    sys.exit(main())

  File "multicast-relay.py", line 985, in main

    packetRelay.addListener(addr, port, relay[1])

  File "multicast-relay.py", line 304, in addListener

    self.transmitters.append({'relay': {'addr': listenIP, 'port': port}, 'interface': ifname, 'addr': ip, 'mac': mac, 'netmask': netmask, 'broadcast': broadcast, 'socket': tx, 'service': service})

UnboundLocalError: local variable 'listenIP' referenced before assignment
`

**Comment by alsmith** [comment]
Fix checked in - will merge to master.
