### ISSUE TITLE
Debian 11 compatibility

### ISSUE THREAD

**Issue by lsiepel** [alsmith/multicast-relay#58]
Been using this for over a year with great success, But since i upgraded Debian to version 11 it stopped working. I tried to satisfy all dependencies, but somehow it doesn't work. Can anyone point me in the right direction (and update documentation if needed)

As netifaces is required, i installed it:

```
me@host:~/scripts$ sudo pip install netifaces

Requirement already satisfied: netifaces in /usr/local/lib/python3.9/dist-packages (0.11.0)
```

```
me@host:~/scripts$ sudo /opt/multicast-relay/multicast-relay.py --interface enp3s0.2 enp3s0.3 --noMDNS

Traceback (most recent call last):
  File "/opt/multicast-relay/multicast-relay.py", line 1018, in <module>
    sys.exit(main())
  File "/opt/multicast-relay/multicast-relay.py", line 975, in main
    logger               = logger)
  File "/opt/multicast-relay/multicast-relay.py", line 194, in __init__
    self.nif = Netifaces(homebrewNetifaces, ifNameStructLen)
  File "/opt/multicast-relay/multicast-relay.py", line 73, in __init__
    import netifaces
ImportError: No module named netifaces
```
Tried to remove and install again, but somehow the script cannot import it.

**Comment by alsmith** [comment]
Hi @lsiepel - I suspect that the relay is picking up python2 where as pip installed netifaces for python3.

Try editing the first line of the relay to say `#!/usr/bin/env python3`

Best of luck! Al.
