### ISSUE TITLE
Android client can't see Chromecast Speaker Groups 

### ISSUE THREAD

**Issue by stonith** [alsmith/multicast-relay#61]
Hi,

I realize this is likely not a multicast-relay specific issue but I thought I'd ask since chromecast is mentioned in the readme.

Without multicast-relay on my Unifi UDM Pro, iOS in a different plan would only see my chromecast speaker groups in the Spotify app, and not other apps like Google Home or Plexamp. Android would never see them however. 

When running scyto's docker container however, my iOS devices now see the speaker groups in Google Home and Plexamp while my Android devices still don't see them. 

Any ideas as to what the deal is with Android clients and chromecast speaker groups in different vlans?

Thanks.

**Comment by stonith** [comment]
I finally got this working on Android devices by using https://github.com/marjohn56/udpbroadcastrelay

**Comment by alsmith** [comment]
Hi Darren,

Did you have to supply any parameters to get this to work ?

**Comment by stonith** [comment]
> Hi Darren,
> 
> Did you have to supply any parameters to get this to work ?

I ended up replacing multicast-relay with udpbroastcastrelay. I think the key for chromecast speaker groups is ["set the source ip to the address of the outgoing interface and the source UDP port to the same as the destination port"](https://github.com/marjohn56/udpbroadcastrelay/blob/master/README.md?plain=1#L52-L56)
