### ISSUE TITLE
set REMOTE_HOST to a subnet?

### ISSUE THREAD

**Issue by eusmark** [alsmith/multicast-relay#64]
This is a fantastic project.  I have a need to have the --listen flag able to receive connections from a subnet that is dynamically setup.  For example "--listen 10.111.25.0/26".

**Comment by alsmith** [comment]
Hi Mark - appreciate the feedback.

I'll merge the code that will do this in the next few minutes.

**Comment by eusmark** [comment]
Thank you so much for the quick response and fix!

I just tried it out and getting an exception.  This appears to be a python3 vs python2 syntax issue.  Will see if there is a quick fix, otherwise, will install python2 on this system.

eusmark@fe1-net2-relay: $ git clone https://github.com/alsmith/multicast-relay.git
Cloning into 'multicast-relay'...
remote: Enumerating objects: 324, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 324 (delta 16), reused 24 (delta 16), pack-reused 295
Receiving objects: 100% (324/324), 119.07 KiB | 812.00 KiB/s, done.
Resolving deltas: 100% (194/194), done.
eusmark@fe1-net2-relay: $ cd multicast-relay
eusmark@fe1-net2-relay: multicast-relay$ sudo python3 ./multicast-relay.py --interfaces ens160 --listen 10.111.25.0/27 --noMDNS --noSSDP --noSonosDiscovery --relay 239.255.255.250:3702 --verbose --foreground
Apr-28 09:41:45 ./multicast-relay.py INFO: Adding multicast relay for 239.255.255.250:3702
Traceback (most recent call last):
  File "./multicast-relay.py", line 1028, in <module>
    sys.exit(main())
  File "./multicast-relay.py", line 1025, in main
    packetRelay.loop()
  File "./multicast-relay.py", line 507, in loop
    if not len(list(filter(lambda addr: PacketRelay.onNetwork(remoteAddr[0], addr[0], PacketRelay.cidrToNetmask(addr[1])), self.listenAddr))):
  File "./multicast-relay.py", line 507, in <lambda>
    if not len(list(filter(lambda addr: PacketRelay.onNetwork(remoteAddr[0], addr[0], PacketRelay.cidrToNetmask(addr[1])), self.listenAddr))):
  File "./multicast-relay.py", line 874, in cidrToNetmask
    return socket.inet_ntoa(struct.pack('!I', (1 << 32) - (1 << (32 - bits))))
TypeError: unsupported operand type(s) for -: 'int' and 'str'
eusmark@fe1-net2-relay:~/multicast-relay$

**Comment by alsmith** [comment]
Fix pushed - sorry about that.

**Comment by eusmark** [comment]
Just tested and works like a champ!  Thank you!

**Comment by eusmark** [comment]
Will this continue to work on python2 as well?

**Comment by alsmith** [comment]
But basically if it worked on python2 yesterday, it will still work today.
