### ISSUE TITLE
latest commit broken

### ISSUE THREAD

**Issue by itiligent** [alsmith/multicast-relay#75]
Hi,

Thanks for your handy script.

OS: Openwrt 22.03.5 /  python3-light & python3-netifaces installed.  (no need to follow th eold OWRT instructions for python2.7 it seems)

The previous commit 2c0e4c7 seems to work fine, but latest commit  030451  "additional mechanism for Sonos to dissover itself" returns the following ...

python /root/multicast-relay.py  --interfaces br-lan br-iot

Traceback (most recent call last):
  File "/root/multicast-relay.py", line 1030, in <module>
    sys.exit(main())
  File "/root/multicast-relay.py", line 959, in main
    relays.add(('%s:%d' % (PacketRelay.BROADCAST, '1900'), 'Sonos Discovery'))
TypeError: %d format: a real number is required, not str

**Comment by alsmith** [comment]
Sorry about that - fixed.
