### ISSUE TITLE
easy-install-3.5 TLS 1.2 error

### ISSUE THREAD

**Issue by wessjan** [alsmith/multicast-relay#8]
Hi there,
I would love to enhance my zeroshell installation with the multicast-relay to get my Sonos controllers and speakers connected again. But when following the installation i struggle with

> Searching for netifaces
> Reading https://pypi.python.org/simple/netifaces/
> Download error on https://pypi.python.org/simple/netifaces/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) -- Some packages may not be found!
> Couldn't find index page for 'netifaces' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.python.org/simple/
> Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) -- Some packages may not be found!
> No local packages or download links found for netifaces
> error: Could not find suitable distribution for Requirement.parse('netifaces')

I know, that pypi.python.org has banned TLS 1.1 connection. I've checked the openssl version installed would support TLS 1.2 (OpenSSL 1.0.2o  27 Mar 2018), but I've no clue who to convince easy-install to use TLS 1.2. 
Is there a way to either update easy-install or to configure it to use TLS 1.2?
Best regards
Jan

**Comment by alsmith** [comment]
Hi Jan,

Can you let me know what version of ZeroShell you're using ?

It might be possible to use 'pip' instead; try this and see if it works for you:

`curl https://bootstrap.pypa.io/get-pip.py | python`

And then:

`pip install netifaces`

Let me know how you get on...

Regards,
Al.

**Comment by wessjan** [comment]
Hi Al,
thanks for the quick answer. I'm running Release 3.9.0 with Kernel 4.14.29-ZS-64. Additionally packages installed are:
- Development Environment (C,C++ and Headers) 4.9.2 
- Python Interpreter 3.5.1 

But unfortunatly curl also returns a TLS1 error:

> curl:

 (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by wessjan** [comment]
UPDATE:
I downloaded the get-pip.py script with my windows machine, transferred it to zeroshell and started it with python. But that script will download as well using connections secured by TLS1 only and fails:

> (DEVEL) ~> python get-pip.py
> Collecting pip
>   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)'),)': /simple/pip/
>   Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)'),)': /simple/pip/
>   Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)'),)': /simple/pip/
>   Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)'),)': /simple/pip/
>   Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)'),)': /simple/pip/
>   Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)'),)) - skipping
>   Could not find a version that satisfies the requirement pip (from versions: )
> No matching distribution found for pip
> Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)'),)) - skipping
>

**Comment by alsmith** [comment]
Hm. That sounds like an issue that you ought to take up with the ZeroShell maintainer... curl really ought to work without a problem. If there's an issue with the underlying openssl libs or config then that ought to get resolved first. Sorry to pass the buck here!

**Comment by wessjan** [comment]
Thanks anyway. I found a code snippet to check the OpenSSL version within python:
>>> print (ssl.OPENSSL_VERSION)
OpenSSL 0.9.8zh 3 Dec 2015
The maintainer has definitely to provide an updated python environment with the current OpenSSL libs compiled in.
