### ISSUE TITLE
IP address 192.168.0.255 is neither a multicast nor a broadcast address even after 461d1c9

### ISSUE THREAD

**Issue by LyraelRayne** [alsmith/multicast-relay#89]
Hi there, I am using commit `461d1c9` and still am getting `IP address 192.168.0.255 is neither a multicast nor a broadcast address` for `python3 ./multicast-relay.py --verbose --foreground --noSSDP --noMDNS --noSonosDiscovery --relay 192.168.0.255:56700 --interfaces eth0 eth0.10` 

Interface details
```
eth0        inet addr:192.168.0.86      Bcast: 192.168.0.255    Mask:255.255.255.0
eth0.10   inet addr:192.168.10.169  Bcast: 192.168.10.255  Mask:255.255.255.0
```

Am I doing something wrong?

**Comment by alsmith** [comment]
Hi @LyraelRayne 

Try this instead: `./multicast-relay.py --verbose --foreground --noSSDP --noMDNS --noSonosDiscovery --relay 255.255.255.255:56700 --interfaces eth0 eth0.10`

**Comment by LyraelRayne** [comment]
Oh! I think I misunderstood what the fix did. When I specify `255.255.255.255` it does in fact forward broadcasts sent to `192.168.0.255`. Thank you!
