### ISSUE TITLE
Specify subnets rather than interfaces?

### ISSUE THREAD

**Issue by tacomilkshake** [alsmith/multicast-relay#9]
Thanks for making this script. I have two subnets each with Sonos speakers. Each device on both subnets can access the devices on the other subnet. I'd love to have all speakers in one controller.

I've got a Linux box (that isn't the router) that can access both subnets and all devices. Anyway to do something similar to this:

./multicast-relay.py --interfaces 192.168.0.1/24 192.168.1.1/24

Instead of specifying physical network interfaces?

**Comment by alsmith** [comment]
Sure thing - I’ll get to it shortly...

**Comment by alsmith** [comment]
Just checked in code to do this... have a go and see how you get on...

**Comment by jamiesteven** [comment]
Excellent thank you.

Ran:
./multicast-relay.py --interfaces 192.168.0.0/24 192.168.1.0/24

Got:
Interface 192.168.1.0/24 does not exist.

This Ubuntu Linux box only has one NIC and only one interface configured. While it can access both subnets, it's interface is only through the primary 192.168.0.0/24 subnet.

Might not be possible in a Mac with only one interface.

**Comment by alsmith** [comment]
I suspect that if you have just one interface that you're using interface aliasing to assign the second IP#... if you could paste the output of this, I can verify and might be able to work around the issue for you.

`cut -f1 -d: /proc/net/dev`

**Comment by alsmith** [comment]
Ok, I checked in some experimental code to https://github.com/alsmith/multicast-relay/tree/one_interface - let me know how you get on. Do be mindful that you might cause a broadcast storm that'll bring your network down... but hey give it a try!

**Comment by alsmith** [comment]
Oh and you'll need to just specify the single physical interface and also add `--one_interface`, like this - no need to specify each network separately by IP address.

`./multicast-relay.py --interfaces en0 --one_interface --foreground --verbose`
